"""empty message

Revision ID: 00de21efa961
Revises: 44fc26233b95
Create Date: 2018-01-06 03:12:00.669368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00de21efa961'
down_revision = '44fc26233b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
